ms-settings:
  port: 8010
  path: /api/v1/settings
  complete-path: http://settings:${ms-settings.port}

db-config:
  domain: db-document-manager:5432
  name: atenea_document_manager
  user: postgres
  password: VA@Atenea2023